export const DEFAULT_LANGUAGE = "en";

export const SUPPORTED_LANGUAGES = [
  { code: "en", appStoreLocale: "en-US", name: "English", nativeName: "English" },
  { code: "zh-Hans", appStoreLocale: "zh-Hans", name: "Chinese Simplified", nativeName: "简体中文" },
  { code: "es", appStoreLocale: "es-ES", name: "Spanish", nativeName: "Español" },
  { code: "hi", appStoreLocale: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ar", appStoreLocale: "ar", name: "Arabic", nativeName: "العربية", dir: "rtl" },
  { code: "pt-BR", appStoreLocale: "pt-BR", name: "Portuguese Brazil", nativeName: "Português (Brasil)" },
  { code: "fr", appStoreLocale: "fr-FR", name: "French", nativeName: "Français" },
  { code: "de", appStoreLocale: "de-DE", name: "German", nativeName: "Deutsch" },
  { code: "ja", appStoreLocale: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", appStoreLocale: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ru", appStoreLocale: "ru", name: "Russian", nativeName: "Русский" },
  { code: "id", appStoreLocale: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "tr", appStoreLocale: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "it", appStoreLocale: "it", name: "Italian", nativeName: "Italiano" },
  { code: "vi", appStoreLocale: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
] as const;

export type AppLanguage = (typeof SUPPORTED_LANGUAGES)[number]["code"];

type TranslationMap = Record<string, string>;

export function isSupportedLanguage(value: unknown): value is AppLanguage {
  return (
    typeof value === "string" &&
    SUPPORTED_LANGUAGES.some((language) => language.code === value)
  );
}

export function normalizeLanguage(value: unknown): AppLanguage {
  return isSupportedLanguage(value) ? value : DEFAULT_LANGUAGE;
}

export function getLanguageDirection(language: AppLanguage): "ltr" | "rtl" {
  return SUPPORTED_LANGUAGES.find((entry) => entry.code === language)?.dir === "rtl"
    ? "rtl"
    : "ltr";
}

export function toIntlLocale(language: AppLanguage): string {
  return SUPPORTED_LANGUAGES.find((entry) => entry.code === language)?.appStoreLocale ?? "en-US";
}

export function translateText(text: string, language: AppLanguage): string {
  if (language === DEFAULT_LANGUAGE) return text;
  const trimmed = text.trim();
  if (!trimmed) return text;

  const translated = translateTrimmed(trimmed, language);
  if (!translated || translated === trimmed) return text;

  const leading = text.match(/^\s*/)?.[0] ?? "";
  const trailing = text.match(/\s*$/)?.[0] ?? "";
  return `${leading}${translated}${trailing}`;
}

export function t(text: string, language: AppLanguage): string {
  return translateTrimmed(text, language) ?? text;
}

function translateTrimmed(text: string, language: AppLanguage): string | undefined {
  const dictionary = TRANSLATIONS[language];
  if (!dictionary) return undefined;
  if (dictionary[text]) return dictionary[text];

  const levelOf = /^Level (\d+) of (\d+)$/.exec(text);
  if (levelOf) {
    return `${dictionary.Level ?? "Level"} ${levelOf[1]} ${dictionary.of ?? "of"} ${levelOf[2]}`;
  }

  const levelSlash = /^Level (\d+) \/ (\d+)$/.exec(text);
  if (levelSlash) {
    return `${dictionary.Level ?? "Level"} ${levelSlash[1]} / ${levelSlash[2]}`;
  }

  const quests = /^(\d+)\/(\d+) quests complete today\.$/.exec(text);
  if (quests) {
    return `${quests[1]}/${quests[2]} ${dictionary["quests complete today."] ?? "quests complete today."}`;
  }

  const dailyPrize = /^Complete 4 of 6 quests to claim the daily prize of (\d+) gold coins\.$/.exec(
    text,
  );
  if (dailyPrize) {
    return `${dictionary["Complete 4 of 6 quests to claim the daily prize of"] ?? "Complete 4 of 6 quests to claim the daily prize of"} ${dailyPrize[1]} ${dictionary["gold coins."] ?? "gold coins."}`;
  }

  const unlockedAt = /^Unlocked at level (\d+)\.$/.exec(text);
  if (unlockedAt) {
    return `${dictionary["Unlocked at level"] ?? "Unlocked at level"} ${unlockedAt[1]}.`;
  }

  const secretUnlock = /^Secret unlock at level (\d+)$/.exec(text);
  if (secretUnlock) {
    return `${dictionary["Secret unlock at level"] ?? "Secret unlock at level"} ${secretUnlock[1]}`;
  }

  const owned = /^Owned: (\d+)$/.exec(text);
  if (owned) {
    return `${dictionary["Owned:"] ?? "Owned:"} ${owned[1]}`;
  }

  const noCoins = /^You need (\d+) gold coins? to buy (.+)\.$/.exec(text);
  if (noCoins) {
    return `${dictionary["You need"] ?? "You need"} ${noCoins[1]} ${dictionary["gold coins"] ?? "gold coins"} ${dictionary["to buy"] ?? "to buy"} ${noCoins[2]}.`;
  }

  const addedInventory = /^(.+) added to your inventory\.$/.exec(text);
  if (addedInventory) {
    return `${addedInventory[1]} ${dictionary["added to your inventory."] ?? "added to your inventory."}`;
  }

  const introducedAt = /^(.+) is introduced at level (\d+)\.$/.exec(text);
  if (introducedAt) {
    return `${introducedAt[1]} ${dictionary["is introduced at level"] ?? "is introduced at level"} ${introducedAt[2]}.`;
  }

  return undefined;
}

const TRANSLATIONS: Partial<Record<AppLanguage, TranslationMap>> = {
  "zh-Hans": {
    Menu: "菜单",
    Back: "返回",
    "Back to game": "返回游戏",
    Shop: "商店",
    Play: "开始",
    Map: "地图",
    Collection: "收藏",
    Settings: "设置",
    Profile: "个人资料",
    Lab: "实验室",
    Library: "图鉴",
    Level: "关卡",
    of: "共",
    "Free Lab": "免费实验室",
    "Pro Lab active": "专业实验室已启用",
    "PLAYER PROFILE": "玩家资料",
    "Fusion Rush Chemist": "Fusion Rush 化学家",
    "PRO LAB PACK ACTIVE": "专业实验室包已启用",
    "Total Score": "总分",
    career: "生涯",
    "Gold Coins": "金币",
    "shop currency": "商店货币",
    "Daily Streak": "每日连续",
    claimed: "已领取",
    active: "进行中",
    "Best Combo": "最佳连击",
    "no record yet": "暂无记录",
    "Highest Atom": "最高原子",
    Elements: "元素",
    Stars: "星级",
    perfect: "完美",
    Display: "显示",
    Theme: "主题",
    Dark: "深色",
    Light: "浅色",
    Language: "语言",
    "Daily Lab": "每日实验室",
    "quests complete today.": "个任务今日完成。",
    "Complete 4 of 6 quests to claim the daily prize of": "完成 6 个任务中的 4 个以领取每日奖励",
    "gold coins.": "金币。",
    "gold coins": "金币",
    " (includes +2 Pro bonus)": "（包含 +2 专业奖励）",
    Records: "记录",
    "Best challenge score": "最佳挑战分数",
    "Badges earned": "已获得徽章",
    "Campaign levels unlocked": "已解锁战役关卡",
    "Periodic table progress": "元素周期表进度",
    "Lock stages": "锁定关卡",
    "Unlock all stages": "解锁所有关卡",
    "Enter unlock password": "输入解锁密码",
    "Wrong password.": "密码错误。",
    "Convert points into gold coins and stock your next run": "将积分兑换为金币，为下一局做好准备",
    "ONE-TIME UPGRADE": "一次性升级",
    "Pro Lab Pack - Lifetime": "专业实验室包 - 终身",
    Available: "可用",
    "A one-time premium upgrade for long-term progression.": "用于长期进度的一次性高级升级。",
    "Remove forced interstitial ads.": "移除强制插屏广告。",
    "Unlock the Pro Lab profile badge.": "解锁专业实验室资料徽章。",
    "Get 50 starting gold coins.": "获得 50 枚初始金币。",
    "Get +2 extra gold coins on each daily gold claim.": "每次领取每日金币时额外获得 +2 金币。",
    Restore: "恢复",
    "Unlock Pack": "解锁礼包",
    "Manage Purchases": "管理购买",
    "APP STORE COINS": "APP STORE 金币",
    "Buy gold coins": "购买金币",
    "Watch rewarded ad for +1 coin": "观看奖励广告获得 +1 金币",
    "App Store": "App Store",
    "INVENTORY POWER-UPS": "库存强化",
    "Stock your next run": "为下一局备货",
    "Buy extra inventory copies with gold coins. Before each level, you can choose up to 3 inventory power-ups to start with.":
      "用金币购买额外库存。每个关卡开始前，你最多可选择 3 个库存强化。",
    Secret: "秘密",
    "Owned:": "拥有：",
    "Unlocked at level": "在关卡解锁",
    "Secret unlock at level": "秘密解锁于关卡",
    "You need": "你需要",
    "to buy": "购买",
    "added to your inventory.": "已加入库存。",
    "is introduced at level": "将在关卡引入",
    Support: "支持",
    "Need help with Atomic Fusion Rush? We are happy to help.": "需要 Atomic Fusion Rush 帮助？我们很乐意协助。",
    Contact: "联系",
    "Typical response time: 1-3 business days.": "通常回复时间：1-3 个工作日。",
    "How to Report an Issue": "如何报告问题",
    "Terms of Service": "服务条款",
    "Privacy Policy": "隐私政策",
    "Last updated:": "最后更新：",
  },
  es: {
    Menu: "Menú",
    Back: "Atrás",
    "Back to game": "Volver al juego",
    Shop: "Tienda",
    Play: "Jugar",
    Map: "Mapa",
    Collection: "Colección",
    Settings: "Ajustes",
    Profile: "Perfil",
    Lab: "Laboratorio",
    Library: "Biblioteca",
    Level: "Nivel",
    of: "de",
    "Free Lab": "Laboratorio gratis",
    "Pro Lab active": "Laboratorio Pro activo",
    "PLAYER PROFILE": "PERFIL DEL JUGADOR",
    "Fusion Rush Chemist": "Químico de Fusion Rush",
    "PRO LAB PACK ACTIVE": "PACK LAB PRO ACTIVO",
    "Total Score": "Puntuación total",
    career: "carrera",
    "Gold Coins": "Monedas de oro",
    "shop currency": "moneda de tienda",
    "Daily Streak": "Racha diaria",
    claimed: "reclamado",
    active: "activo",
    "Best Combo": "Mejor combo",
    "no record yet": "sin récord",
    "Highest Atom": "Átomo más alto",
    Elements: "Elementos",
    Stars: "Estrellas",
    perfect: "perfecto",
    Display: "Pantalla",
    Theme: "Tema",
    Dark: "Oscuro",
    Light: "Claro",
    Language: "Idioma",
    "Daily Lab": "Laboratorio diario",
    "quests complete today.": "misiones completadas hoy.",
    "Complete 4 of 6 quests to claim the daily prize of": "Completa 4 de 6 misiones para reclamar el premio diario de",
    "gold coins.": "monedas de oro.",
    "gold coins": "monedas de oro",
    " (includes +2 Pro bonus)": " (incluye +2 bono Pro)",
    Records: "Récords",
    "Best challenge score": "Mejor puntuación de desafío",
    "Badges earned": "Insignias ganadas",
    "Campaign levels unlocked": "Niveles de campaña desbloqueados",
    "Periodic table progress": "Progreso de la tabla periódica",
    "Lock stages": "Bloquear fases",
    "Unlock all stages": "Desbloquear todas las fases",
    "Enter unlock password": "Introduce la contraseña",
    "Wrong password.": "Contraseña incorrecta.",
    "Convert points into gold coins and stock your next run": "Convierte puntos en monedas de oro y prepara tu próxima partida",
    "ONE-TIME UPGRADE": "MEJORA ÚNICA",
    "Pro Lab Pack - Lifetime": "Pack Lab Pro - De por vida",
    Available: "Disponible",
    "A one-time premium upgrade for long-term progression.": "Una mejora premium única para progresar a largo plazo.",
    "Remove forced interstitial ads.": "Elimina anuncios intersticiales obligatorios.",
    "Unlock the Pro Lab profile badge.": "Desbloquea la insignia de perfil Lab Pro.",
    "Get 50 starting gold coins.": "Obtén 50 monedas de oro iniciales.",
    "Get +2 extra gold coins on each daily gold claim.": "Obtén +2 monedas de oro extra en cada recompensa diaria.",
    Restore: "Restaurar",
    "Unlock Pack": "Desbloquear pack",
    "Manage Purchases": "Gestionar compras",
    "APP STORE COINS": "MONEDAS APP STORE",
    "Buy gold coins": "Comprar monedas de oro",
    "Watch rewarded ad for +1 coin": "Ver anuncio recompensado por +1 moneda",
    "App Store": "App Store",
    "INVENTORY POWER-UPS": "POTENCIADORES",
    "Stock your next run": "Prepara tu próxima partida",
    "Buy extra inventory copies with gold coins. Before each level, you can choose up to 3 inventory power-ups to start with.":
      "Compra copias extra con monedas de oro. Antes de cada nivel puedes elegir hasta 3 potenciadores iniciales.",
    Secret: "Secreto",
    "Owned:": "Tienes:",
    "Unlocked at level": "Desbloqueado en el nivel",
    "Secret unlock at level": "Se desbloquea en secreto en el nivel",
    "You need": "Necesitas",
    "to buy": "para comprar",
    "added to your inventory.": "añadido a tu inventario.",
    "is introduced at level": "se presenta en el nivel",
    Support: "Soporte",
    "Need help with Atomic Fusion Rush? We are happy to help.": "¿Necesitas ayuda con Atomic Fusion Rush? Encantados de ayudarte.",
    Contact: "Contacto",
    "Typical response time: 1-3 business days.": "Tiempo de respuesta habitual: 1-3 días laborables.",
    "How to Report an Issue": "Cómo informar de un problema",
    "Terms of Service": "Términos del servicio",
    "Privacy Policy": "Política de privacidad",
    "Last updated:": "Última actualización:",
  },
  hi: {
    Menu: "मेनू",
    Back: "वापस",
    Shop: "दुकान",
    Play: "खेलें",
    Map: "मानचित्र",
    Collection: "संग्रह",
    Settings: "सेटिंग्स",
    Profile: "प्रोफाइल",
    Lab: "लैब",
    Library: "लाइब्रेरी",
    Level: "स्तर",
    of: "में से",
    "Free Lab": "मुफ्त लैब",
    "Pro Lab active": "प्रो लैब सक्रिय",
    "PLAYER PROFILE": "खिलाड़ी प्रोफाइल",
    "Fusion Rush Chemist": "Fusion Rush रसायनज्ञ",
    "Total Score": "कुल स्कोर",
    career: "करियर",
    "Gold Coins": "सोने के सिक्के",
    "Daily Streak": "दैनिक क्रम",
    claimed: "ले लिया",
    active: "सक्रिय",
    "Best Combo": "सर्वश्रेष्ठ कॉम्बो",
    "Highest Atom": "सबसे ऊँचा परमाणु",
    Elements: "तत्व",
    Stars: "सितारे",
    Display: "दिखावट",
    Theme: "थीम",
    Dark: "डार्क",
    Light: "लाइट",
    Language: "भाषा",
    "Daily Lab": "दैनिक लैब",
    "quests complete today.": "क्वेस्ट आज पूरी हुईं।",
    Records: "रिकॉर्ड",
    "ONE-TIME UPGRADE": "एक बार का अपग्रेड",
    "Pro Lab Pack - Lifetime": "प्रो लैब पैक - आजीवन",
    Available: "उपलब्ध",
    Restore: "पुनर्स्थापित करें",
    "Unlock Pack": "पैक अनलॉक करें",
    "Manage Purchases": "खरीद प्रबंधित करें",
    "Buy gold coins": "सोने के सिक्के खरीदें",
    Secret: "गुप्त",
    "Owned:": "मौजूद:",
    Support: "सहायता",
    Contact: "संपर्क",
    "Terms of Service": "सेवा की शर्तें",
    "Privacy Policy": "गोपनीयता नीति",
  },
  ar: {
    Menu: "القائمة",
    Back: "رجوع",
    Shop: "المتجر",
    Play: "العب",
    Map: "الخريطة",
    Collection: "المجموعة",
    Settings: "الإعدادات",
    Profile: "الملف الشخصي",
    Lab: "المختبر",
    Library: "المكتبة",
    Level: "المستوى",
    of: "من",
    "Free Lab": "مختبر مجاني",
    "Pro Lab active": "مختبر Pro نشط",
    "PLAYER PROFILE": "ملف اللاعب",
    "Fusion Rush Chemist": "كيميائي Fusion Rush",
    "Total Score": "المجموع",
    career: "المسيرة",
    "Gold Coins": "عملات ذهبية",
    "Daily Streak": "السلسلة اليومية",
    claimed: "تم الاستلام",
    active: "نشط",
    "Best Combo": "أفضل سلسلة",
    "Highest Atom": "أعلى ذرة",
    Elements: "العناصر",
    Stars: "نجوم",
    Display: "العرض",
    Theme: "السمة",
    Dark: "داكن",
    Light: "فاتح",
    Language: "اللغة",
    "Daily Lab": "المختبر اليومي",
    "quests complete today.": "مهام مكتملة اليوم.",
    Records: "السجلات",
    "ONE-TIME UPGRADE": "ترقية لمرة واحدة",
    "Pro Lab Pack - Lifetime": "حزمة مختبر Pro - مدى الحياة",
    Available: "متاح",
    Restore: "استعادة",
    "Unlock Pack": "فتح الحزمة",
    "Manage Purchases": "إدارة المشتريات",
    "Buy gold coins": "شراء عملات ذهبية",
    Secret: "سري",
    "Owned:": "مملوك:",
    Support: "الدعم",
    Contact: "اتصال",
    "Terms of Service": "شروط الخدمة",
    "Privacy Policy": "سياسة الخصوصية",
  },
  "pt-BR": {
    Menu: "Menu",
    Back: "Voltar",
    Shop: "Loja",
    Play: "Jogar",
    Map: "Mapa",
    Collection: "Coleção",
    Settings: "Ajustes",
    Profile: "Perfil",
    Lab: "Laboratório",
    Library: "Biblioteca",
    Level: "Nível",
    of: "de",
    "PLAYER PROFILE": "PERFIL DO JOGADOR",
    "Total Score": "Pontuação total",
    "Gold Coins": "Moedas de ouro",
    "Daily Streak": "Sequência diária",
    "Best Combo": "Melhor combo",
    Elements: "Elementos",
    Stars: "Estrelas",
    Display: "Tela",
    Theme: "Tema",
    Dark: "Escuro",
    Light: "Claro",
    Language: "Idioma",
    "Daily Lab": "Laboratório diário",
    Records: "Recordes",
    "ONE-TIME UPGRADE": "MELHORIA ÚNICA",
    "Pro Lab Pack - Lifetime": "Pacote Lab Pro - Vitalício",
    Available: "Disponível",
    Restore: "Restaurar",
    "Unlock Pack": "Desbloquear pacote",
    "Manage Purchases": "Gerenciar compras",
    "Buy gold coins": "Comprar moedas de ouro",
    Secret: "Secreto",
    Support: "Suporte",
    Contact: "Contato",
    "Terms of Service": "Termos de serviço",
    "Privacy Policy": "Política de privacidade",
  },
};

for (const language of ["fr", "de", "ja", "ko", "ru", "id", "tr", "it", "vi"] as const) {
  TRANSLATIONS[language] = makeCompactTranslation(language);
}

function makeCompactTranslation(language: Exclude<AppLanguage, "en" | "zh-Hans" | "es" | "hi" | "ar" | "pt-BR">): TranslationMap {
  const compact: Record<typeof language, TranslationMap> = {
    fr: {
      Menu: "Menu",
      Back: "Retour",
      Shop: "Boutique",
      Play: "Jouer",
      Map: "Carte",
      Collection: "Collection",
      Settings: "Réglages",
      Profile: "Profil",
      Lab: "Labo",
      Library: "Bibliothèque",
      Level: "Niveau",
      of: "sur",
      "PLAYER PROFILE": "PROFIL JOUEUR",
      "Total Score": "Score total",
      "Gold Coins": "Pièces d’or",
      "Daily Streak": "Série quotidienne",
      "Best Combo": "Meilleur combo",
      Elements: "Éléments",
      Stars: "Étoiles",
      Display: "Affichage",
      Theme: "Thème",
      Dark: "Sombre",
      Light: "Clair",
      Language: "Langue",
      "Daily Lab": "Labo quotidien",
      Records: "Records",
      "Pro Lab Pack - Lifetime": "Pack Labo Pro - À vie",
      Available: "Disponible",
      Restore: "Restaurer",
      "Unlock Pack": "Débloquer le pack",
      "Manage Purchases": "Gérer les achats",
      "Buy gold coins": "Acheter des pièces d’or",
      Secret: "Secret",
      Support: "Assistance",
      Contact: "Contact",
    },
    de: {
      Menu: "Menü",
      Back: "Zurück",
      Shop: "Shop",
      Play: "Spielen",
      Map: "Karte",
      Collection: "Sammlung",
      Settings: "Einstellungen",
      Profile: "Profil",
      Lab: "Labor",
      Library: "Bibliothek",
      Level: "Level",
      of: "von",
      "PLAYER PROFILE": "SPIELERPROFIL",
      "Total Score": "Gesamtpunktzahl",
      "Gold Coins": "Goldmünzen",
      "Daily Streak": "Tages-Serie",
      "Best Combo": "Beste Kombo",
      Elements: "Elemente",
      Stars: "Sterne",
      Display: "Anzeige",
      Theme: "Design",
      Dark: "Dunkel",
      Light: "Hell",
      Language: "Sprache",
      "Daily Lab": "Tageslabor",
      Records: "Rekorde",
      "Pro Lab Pack - Lifetime": "Pro-Labor-Paket - Lebenslang",
      Available: "Verfügbar",
      Restore: "Wiederherstellen",
      "Unlock Pack": "Paket freischalten",
      "Manage Purchases": "Käufe verwalten",
      "Buy gold coins": "Goldmünzen kaufen",
      Secret: "Geheim",
      Support: "Support",
      Contact: "Kontakt",
    },
    ja: {
      Menu: "メニュー",
      Back: "戻る",
      Shop: "ショップ",
      Play: "プレイ",
      Map: "マップ",
      Collection: "コレクション",
      Settings: "設定",
      Profile: "プロフィール",
      Lab: "ラボ",
      Library: "ライブラリ",
      Level: "レベル",
      of: "/",
      "PLAYER PROFILE": "プレイヤープロフィール",
      "Total Score": "合計スコア",
      "Gold Coins": "ゴールドコイン",
      "Daily Streak": "デイリーストリーク",
      "Best Combo": "最高コンボ",
      Elements: "元素",
      Stars: "スター",
      Display: "表示",
      Theme: "テーマ",
      Dark: "ダーク",
      Light: "ライト",
      Language: "言語",
      "Daily Lab": "デイリーラボ",
      Records: "記録",
      "Pro Lab Pack - Lifetime": "プロラボパック - 永久",
      Available: "利用可能",
      Restore: "復元",
      "Unlock Pack": "パックを解除",
      "Manage Purchases": "購入を管理",
      "Buy gold coins": "ゴールドコインを購入",
      Secret: "シークレット",
      Support: "サポート",
      Contact: "連絡先",
    },
    ko: {
      Menu: "메뉴",
      Back: "뒤로",
      Shop: "상점",
      Play: "플레이",
      Map: "지도",
      Collection: "컬렉션",
      Settings: "설정",
      Profile: "프로필",
      Lab: "실험실",
      Library: "라이브러리",
      Level: "레벨",
      of: "/",
      "PLAYER PROFILE": "플레이어 프로필",
      "Total Score": "총점",
      "Gold Coins": "골드 코인",
      "Daily Streak": "일일 연속",
      "Best Combo": "최고 콤보",
      Elements: "원소",
      Stars: "별",
      Display: "표시",
      Theme: "테마",
      Dark: "다크",
      Light: "라이트",
      Language: "언어",
      "Daily Lab": "일일 실험실",
      Records: "기록",
      "Pro Lab Pack - Lifetime": "프로 랩 팩 - 평생",
      Available: "사용 가능",
      Restore: "복원",
      "Unlock Pack": "팩 잠금 해제",
      "Manage Purchases": "구매 관리",
      "Buy gold coins": "골드 코인 구매",
      Secret: "비밀",
      Support: "지원",
      Contact: "문의",
    },
    ru: {
      Menu: "Меню",
      Back: "Назад",
      Shop: "Магазин",
      Play: "Играть",
      Map: "Карта",
      Collection: "Коллекция",
      Settings: "Настройки",
      Profile: "Профиль",
      Lab: "Лаборатория",
      Library: "Библиотека",
      Level: "Уровень",
      of: "из",
      "PLAYER PROFILE": "ПРОФИЛЬ ИГРОКА",
      "Total Score": "Общий счет",
      "Gold Coins": "Золотые монеты",
      "Daily Streak": "Ежедневная серия",
      "Best Combo": "Лучшее комбо",
      Elements: "Элементы",
      Stars: "Звезды",
      Display: "Экран",
      Theme: "Тема",
      Dark: "Темная",
      Light: "Светлая",
      Language: "Язык",
      "Daily Lab": "Ежедневная лаборатория",
      Records: "Рекорды",
      "Pro Lab Pack - Lifetime": "Пакет Pro Lab - навсегда",
      Available: "Доступно",
      Restore: "Восстановить",
      "Unlock Pack": "Разблокировать пакет",
      "Manage Purchases": "Управлять покупками",
      "Buy gold coins": "Купить золотые монеты",
      Secret: "Секрет",
      Support: "Поддержка",
      Contact: "Контакт",
    },
    id: {
      Menu: "Menu",
      Back: "Kembali",
      Shop: "Toko",
      Play: "Main",
      Map: "Peta",
      Collection: "Koleksi",
      Settings: "Pengaturan",
      Profile: "Profil",
      Lab: "Lab",
      Library: "Perpustakaan",
      Level: "Level",
      of: "dari",
      "PLAYER PROFILE": "PROFIL PEMAIN",
      "Total Score": "Skor total",
      "Gold Coins": "Koin emas",
      "Daily Streak": "Rangkaian harian",
      "Best Combo": "Kombo terbaik",
      Elements: "Elemen",
      Stars: "Bintang",
      Display: "Tampilan",
      Theme: "Tema",
      Dark: "Gelap",
      Light: "Terang",
      Language: "Bahasa",
      "Daily Lab": "Lab harian",
      Records: "Rekor",
      "Pro Lab Pack - Lifetime": "Paket Lab Pro - Seumur hidup",
      Available: "Tersedia",
      Restore: "Pulihkan",
      "Unlock Pack": "Buka paket",
      "Manage Purchases": "Kelola pembelian",
      "Buy gold coins": "Beli koin emas",
      Secret: "Rahasia",
      Support: "Dukungan",
      Contact: "Kontak",
    },
    tr: {
      Menu: "Menü",
      Back: "Geri",
      Shop: "Mağaza",
      Play: "Oyna",
      Map: "Harita",
      Collection: "Koleksiyon",
      Settings: "Ayarlar",
      Profile: "Profil",
      Lab: "Laboratuvar",
      Library: "Kütüphane",
      Level: "Seviye",
      of: "/",
      "PLAYER PROFILE": "OYUNCU PROFİLİ",
      "Total Score": "Toplam skor",
      "Gold Coins": "Altın paralar",
      "Daily Streak": "Günlük seri",
      "Best Combo": "En iyi kombo",
      Elements: "Elementler",
      Stars: "Yıldızlar",
      Display: "Görüntü",
      Theme: "Tema",
      Dark: "Koyu",
      Light: "Açık",
      Language: "Dil",
      "Daily Lab": "Günlük laboratuvar",
      Records: "Kayıtlar",
      "Pro Lab Pack - Lifetime": "Pro Lab Paketi - Ömür boyu",
      Available: "Mevcut",
      Restore: "Geri yükle",
      "Unlock Pack": "Paketi aç",
      "Manage Purchases": "Satın almaları yönet",
      "Buy gold coins": "Altın para satın al",
      Secret: "Gizli",
      Support: "Destek",
      Contact: "İletişim",
    },
    it: {
      Menu: "Menu",
      Back: "Indietro",
      Shop: "Negozio",
      Play: "Gioca",
      Map: "Mappa",
      Collection: "Collezione",
      Settings: "Impostazioni",
      Profile: "Profilo",
      Lab: "Laboratorio",
      Library: "Biblioteca",
      Level: "Livello",
      of: "di",
      "PLAYER PROFILE": "PROFILO GIOCATORE",
      "Total Score": "Punteggio totale",
      "Gold Coins": "Monete d’oro",
      "Daily Streak": "Serie giornaliera",
      "Best Combo": "Miglior combo",
      Elements: "Elementi",
      Stars: "Stelle",
      Display: "Schermo",
      Theme: "Tema",
      Dark: "Scuro",
      Light: "Chiaro",
      Language: "Lingua",
      "Daily Lab": "Laboratorio giornaliero",
      Records: "Record",
      "Pro Lab Pack - Lifetime": "Pacchetto Lab Pro - A vita",
      Available: "Disponibile",
      Restore: "Ripristina",
      "Unlock Pack": "Sblocca pacchetto",
      "Manage Purchases": "Gestisci acquisti",
      "Buy gold coins": "Compra monete d’oro",
      Secret: "Segreto",
      Support: "Supporto",
      Contact: "Contatto",
    },
    vi: {
      Menu: "Menu",
      Back: "Quay lại",
      Shop: "Cửa hàng",
      Play: "Chơi",
      Map: "Bản đồ",
      Collection: "Bộ sưu tập",
      Settings: "Cài đặt",
      Profile: "Hồ sơ",
      Lab: "Phòng thí nghiệm",
      Library: "Thư viện",
      Level: "Cấp",
      of: "trên",
      "PLAYER PROFILE": "HỒ SƠ NGƯỜI CHƠI",
      "Total Score": "Tổng điểm",
      "Gold Coins": "Xu vàng",
      "Daily Streak": "Chuỗi hằng ngày",
      "Best Combo": "Combo tốt nhất",
      Elements: "Nguyên tố",
      Stars: "Sao",
      Display: "Hiển thị",
      Theme: "Giao diện",
      Dark: "Tối",
      Light: "Sáng",
      Language: "Ngôn ngữ",
      "Daily Lab": "Phòng thí nghiệm ngày",
      Records: "Kỷ lục",
      "Pro Lab Pack - Lifetime": "Gói Lab Pro - Trọn đời",
      Available: "Có sẵn",
      Restore: "Khôi phục",
      "Unlock Pack": "Mở khóa gói",
      "Manage Purchases": "Quản lý mua hàng",
      "Buy gold coins": "Mua xu vàng",
      Secret: "Bí mật",
      Support: "Hỗ trợ",
      Contact: "Liên hệ",
    },
  };
  return compact[language];
}
