// AUTO-GENERATED by scripts/generate-legal-translations.mjs. Do not edit by hand.

export type LegalLang =
  | "en"
  | "it"
  | "pt-BR"
  | "tr"
  | "ar"
  | "ja"
  | "id"
  | "fr"
  | "ko"
  | "es"
  | "vi"
  | "ru"
  | "zh-Hans"
  | "hi"
  | "de";

export type LegalSection = {
  heading: string;
  body: string[];
  list?: string[];
};

export type LegalDoc = {
  title: string;
  lastUpdatedLabel: string;
  sections: LegalSection[];
};

export const LEGAL_LANGUAGES: { code: LegalLang; label: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", label: "English", dir: "ltr" },
  { code: "it", label: "Italiano", dir: "ltr" },
  { code: "pt-BR", label: "Português (Brasil)", dir: "ltr" },
  { code: "tr", label: "Türkçe", dir: "ltr" },
  { code: "ar", label: "العربية", dir: "rtl" },
  { code: "ja", label: "日本語", dir: "ltr" },
  { code: "id", label: "Bahasa Indonesia", dir: "ltr" },
  { code: "fr", label: "Français", dir: "ltr" },
  { code: "ko", label: "한국어", dir: "ltr" },
  { code: "es", label: "Español", dir: "ltr" },
  { code: "vi", label: "Tiếng Việt", dir: "ltr" },
  { code: "ru", label: "Русский", dir: "ltr" },
  { code: "zh-Hans", label: "简体中文", dir: "ltr" },
  { code: "hi", label: "हिन्दी", dir: "ltr" },
  { code: "de", label: "Deutsch", dir: "ltr" },
];

export const LEGAL_LAST_UPDATED_DATE = "May 22, 2026";

export const PRIVACY_CONTENT: Record<LegalLang, LegalDoc> = {
  "en": {
    "title": "Privacy Policy",
    "lastUpdatedLabel": "Last updated",
    "sections": [
      {
        "heading": "Overview",
        "body": [
          "Atomic Fusion Rush is a puzzle game published by EA Consulting. This policy explains what data is processed when you use the game on web and native mobile builds."
        ]
      },
      {
        "heading": "Data We Process",
        "body": [
          "Depending on platform and features enabled, we may process:"
        ],
        "list": [
          "Gameplay progress such as levels, score, discovered elements, and inventory.",
          "Purchase state and entitlements via RevenueCat and the app store provider.",
          "Crash and diagnostic metadata when analytics/crash tools are enabled.",
          "Advertising consent and ad-delivery metadata for non-Pro users."
        ]
      },
      {
        "heading": "Purchases",
        "body": [
          "In-app purchases are processed through Apple App Store billing and RevenueCat. We do not receive your full payment card details. Purchase status is used to unlock entitlements such as Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Ads and Consent",
        "body": [
          "Non-Pro users may see interstitial ads. We use consent prompts where required by law. You can remove forced ads by purchasing Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Storage and Retention",
        "body": [
          "Gameplay state is primarily stored locally on your device or browser. If you delete the app or clear browser storage, local progress may be lost unless external backup systems are later added."
        ]
      },
      {
        "heading": "Your Rights",
        "body": [
          "Depending on your location, you may have rights to request access, correction, deletion, or limitation of processing for personal data."
        ]
      },
      {
        "heading": "Contact",
        "body": [
          "For privacy requests, contact: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "it": {
    "title": "Informativa sulla privacy",
    "lastUpdatedLabel": "Ultimo aggiornamento",
    "sections": [
      {
        "heading": "Panoramica",
        "body": [
          "Atomic Fusion Rush è un gioco di puzzle pubblicato da EA Consulting. Questa informativa spiega quali dati vengono elaborati quando si utilizza il gioco nelle versioni web e mobile native."
        ]
      },
      {
        "heading": "Dati che elaboriamo",
        "body": [
          "A seconda della piattaforma e delle funzionalità abilitate, potremmo elaborare:"
        ],
        "list": [
          "Progressi di gioco come livelli, punteggio, elementi scoperti e inventario.",
          "Stato di acquisto e diritti tramite RevenueCat e il fornitore dell'app store.",
          "Metadati di crash e diagnostici quando gli strumenti di analisi/crash sono abilitati.",
          "Consenso pubblicitario e metadati di consegna degli annunci per gli utenti non Pro."
        ]
      },
      {
        "heading": "Acquisti",
        "body": [
          "Gli acquisti in-app vengono elaborati tramite la fatturazione dell'Apple App Store e RevenueCat. Non riceviamo i dettagli completi della tua carta di pagamento. Lo stato dell'acquisto viene utilizzato per sbloccare diritti come Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Annunci e consenso",
        "body": [
          "Gli utenti non Pro potrebbero visualizzare annunci interstitial. Utilizziamo richieste di consenso laddove richiesto dalla legge. Puoi rimuovere gli annunci forzati acquistando Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Archiviazione e conservazione",
        "body": [
          "Lo stato di gioco è principalmente archiviato localmente sul tuo dispositivo o browser. Se elimini l'app o cancelli la memoria del browser, i progressi locali potrebbero andare persi a meno che non vengano aggiunti in seguito sistemi di backup esterni."
        ]
      },
      {
        "heading": "I tuoi diritti",
        "body": [
          "A seconda della tua posizione, potresti avere il diritto di richiedere l'accesso, la correzione, la cancellazione o la limitazione del trattamento dei dati personali."
        ]
      },
      {
        "heading": "Contatto",
        "body": [
          "Per richieste sulla privacy, contatta: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "pt-BR": {
    "title": "Política de Privacidade",
    "lastUpdatedLabel": "Última atualização",
    "sections": [
      {
        "heading": "Visão Geral",
        "body": [
          "Atomic Fusion Rush é um jogo de quebra-cabeça publicado pela EA Consulting. Esta política explica quais dados são processados quando você usa o jogo em versões web e mobile nativas."
        ]
      },
      {
        "heading": "Dados que Processamos",
        "body": [
          "Dependendo da plataforma e dos recursos habilitados, podemos processar:"
        ]
      },
      {
        "list": [
          "Progresso do jogo, como níveis, pontuação, elementos descobertos e inventário.",
          "Status de compra e direitos via RevenueCat e o provedor da loja de aplicativos.",
          "Metadados de falhas e diagnósticos quando as ferramentas de análise/falhas estão habilitadas.",
          "Consentimento de publicidade e metadados de entrega de anúncios para usuários não-Pro."
        ]
      },
      {
        "heading": "Compras",
        "body": [
          "As compras dentro do aplicativo são processadas através do faturamento da Apple App Store e do RevenueCat. Não recebemos seus detalhes completos de cartão de pagamento. O status da compra é usado para desbloquear direitos, como Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Anúncios e Consentimento",
        "body": [
          "Usuários não-Pro podem ver anúncios intersticiais. Usamos avisos de consentimento onde exigido por lei. Você pode remover anúncios forçados comprando Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Armazenamento e Retenção",
        "body": [
          "O estado do jogo é armazenado principalmente localmente em seu dispositivo ou navegador. Se você excluir o aplicativo ou limpar o armazenamento do navegador, o progresso local poderá ser perdido, a menos que sistemas de backup externos sejam adicionados posteriormente."
        ]
      },
      {
        "heading": "Seus Direitos",
        "body": [
          "Dependendo da sua localização, você pode ter direitos de solicitar acesso, correção, exclusão ou limitação do processamento de dados pessoais."
        ]
      },
      {
        "heading": "Contato",
        "body": [
          "Para solicitações de privacidade, entre em contato: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "tr": {
    "title": "Gizlilik Politikası",
    "lastUpdatedLabel": "Son güncelleme",
    "sections": [
      {
        "heading": "Genel Bakış",
        "body": [
          "Atomic Fusion Rush, EA Consulting tarafından yayınlanan bir bulmaca oyunudur. Bu politika, oyunu web ve yerel mobil yapılar üzerinde kullandığınızda hangi verilerin işlendiğini açıklar."
        ]
      },
      {
        "heading": "İşlediğimiz Veriler",
        "body": [
          "Platforma ve etkinleştirilen özelliklere bağlı olarak şunları işleyebiliriz:"
        ]
      },
      {
        "list": [
          "Seviyeler, puan, keşfedilen öğeler ve envanter gibi oyun ilerlemesi.",
          "RevenueCat ve uygulama mağazası sağlayıcısı aracılığıyla satın alma durumu ve yetkiler.",
          "Analiz/çökme araçları etkinleştirildiğinde çökme ve teşhis meta verileri.",
          "Pro olmayan kullanıcılar için reklam onayı ve reklam sunumu meta verileri."
        ]
      },
      {
        "heading": "Satın Almalar",
        "body": [
          "Uygulama içi satın almalar Apple App Store faturalandırması ve RevenueCat aracılığıyla işlenir. Tam ödeme kartı bilgilerinizi almıyoruz. Satın alma durumu, Atomic Fusion Lifetime gibi yetkileri açmak için kullanılır."
        ]
      },
      {
        "heading": "Reklamlar ve Onay",
        "body": [
          "Pro olmayan kullanıcılar geçiş reklamları görebilir. Yasal olarak gerekli olduğu durumlarda onay istemleri kullanırız. Atomic Fusion Lifetime satın alarak zorunlu reklamları kaldırabilirsiniz."
        ]
      },
      {
        "heading": "Depolama ve Saklama",
        "body": [
          "Oyun durumu öncelikle cihazınızda veya tarayıcınızda yerel olarak depolanır. Uygulamayı siler veya tarayıcı depolama alanını temizlerseniz, harici yedekleme sistemleri daha sonra eklenmedikçe yerel ilerleme kaybolabilir."
        ]
      },
      {
        "heading": "Haklarınız",
        "body": [
          "Konumunuza bağlı olarak, kişisel veriler için erişim, düzeltme, silme veya işleme sınırlaması talep etme haklarınız olabilir."
        ]
      },
      {
        "heading": "İletişim",
        "body": [
          "Gizlilik talepleri için iletişime geçin: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ar": {
    "title": "سياسة الخصوصية",
    "lastUpdatedLabel": "آخر تحديث",
    "sections": [
      {
        "heading": "نظرة عامة",
        "body": [
          "Atomic Fusion Rush هي لعبة ألغاز من نشر EA Consulting. توضح هذه السياسة البيانات التي تتم معالجتها عند استخدام اللعبة على الويب وإصدارات الهاتف المحمول الأصلية."
        ]
      },
      {
        "heading": "البيانات التي نعالجها",
        "body": [
          "اعتمادًا على النظام الأساسي والميزات المُمكّنة، قد نقوم بمعالجة ما يلي:"
        ],
        "list": [
          "تقدم اللعب مثل المستويات والنتيجة والعناصر المكتشفة والمخزون.",
          "حالة الشراء والاستحقاقات عبر RevenueCat ومزود متجر التطبيقات.",
          "بيانات تعريف الأعطال والتشخيص عند تمكين أدوات التحليلات/الأعطال.",
          "موافقة الإعلانات وبيانات تعريف تسليم الإعلانات للمستخدمين غير المحترفين."
        ]
      },
      {
        "heading": "المشتريات",
        "body": [
          "تتم معالجة عمليات الشراء داخل التطبيق من خلال فواتير Apple App Store وRevenueCat. لا نتلقى تفاصيل بطاقة الدفع الكاملة الخاصة بك. تُستخدم حالة الشراء لفتح الاستحقاقات مثل Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "الإعلانات والموافقة",
        "body": [
          "قد يرى المستخدمون غير المحترفين إعلانات بينية. نستخدم مطالبات الموافقة حيثما يقتضي القانون ذلك. يمكنك إزالة الإعلانات القسرية عن طريق شراء Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "التخزين والاحتفاظ",
        "body": [
          "يتم تخزين حالة اللعب بشكل أساسي محليًا على جهازك أو متصفحك. إذا قمت بحذف التطبيق أو مسح تخزين المتصفح، فقد يُفقد التقدم المحلي ما لم تتم إضافة أنظمة نسخ احتياطي خارجية لاحقًا."
        ]
      },
      {
        "heading": "حقوقك",
        "body": [
          "اعتمادًا على موقعك، قد يكون لديك حقوق لطلب الوصول إلى البيانات الشخصية أو تصحيحها أو حذفها أو تقييد معالجتها."
        ]
      },
      {
        "heading": "جهة الاتصال",
        "body": [
          "لطلبات الخصوصية، اتصل بـ: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ja": {
    "title": "プライバシーポリシー",
    "lastUpdatedLabel": "最終更新日",
    "sections": [
      {
        "heading": "概要",
        "body": [
          "Atomic Fusion Rushは、EA Consultingが公開しているパズルゲームです。このポリシーは、ウェブおよびネイティブモバイルビルドでゲームを使用する際に処理されるデータを説明します。"
        ]
      },
      {
        "heading": "処理するデータ",
        "body": [
          "プラットフォームおよび有効な機能に応じて、以下のデータを処理する場合があります。"
        ],
        "list": [
          "レベル、スコア、発見された要素、インベントリなどのゲームプレイの進行状況。",
          "RevenueCatおよびアプリストアプロバイダーを介した購入状況と資格。",
          "分析/クラッシュツールが有効な場合のクラッシュおよび診断メタデータ。",
          "Proユーザー以外向けの広告同意および広告配信メタデータ。"
        ]
      },
      {
        "heading": "購入",
        "body": [
          "アプリ内購入は、Apple App Storeの請求およびRevenueCatを通じて処理されます。お客様の完全な支払いカードの詳細は受け取りません。購入ステータスは、Atomic Fusion Lifetimeなどの資格を解除するために使用されます。"
        ]
      },
      {
        "heading": "広告と同意",
        "body": [
          "Proユーザー以外は、インタースティシャル広告が表示される場合があります。法律で義務付けられている場合は、同意プロンプトを使用します。Atomic Fusion Lifetimeを購入することで、強制広告を削除できます。"
        ]
      },
      {
        "heading": "ストレージと保持",
        "body": [
          "ゲームプレイの状態は、主にデバイスまたはブラウザにローカルに保存されます。アプリを削除したり、ブラウザのストレージをクリアしたりすると、外部バックアップシステムが後で追加されない限り、ローカルの進行状況が失われる可能性があります。"
        ]
      },
      {
        "heading": "お客様の権利",
        "body": [
          "お客様の所在地によっては、個人データへのアクセス、修正、削除、または処理の制限を要求する権利がある場合があります。"
        ]
      },
      {
        "heading": "連絡先",
        "body": [
          "プライバシーに関するお問い合わせは、eaconsulting.supp@gmail.comまでご連絡ください。"
        ]
      }
    ]
  },
  "id": {
    "title": "Kebijakan Privasi",
    "lastUpdatedLabel": "Terakhir diperbarui",
    "sections": [
      {
        "heading": "Gambaran Umum",
        "body": [
          "Atomic Fusion Rush adalah permainan puzzle yang diterbitkan oleh EA Consulting. Kebijakan ini menjelaskan data apa yang diproses saat Anda menggunakan permainan di web dan aplikasi seluler asli."
        ]
      },
      {
        "heading": "Data yang Kami Proses",
        "body": [
          "Tergantung pada platform dan fitur yang diaktifkan, kami dapat memproses:"
        ],
        "list": [
          "Kemajuan permainan seperti level, skor, elemen yang ditemukan, dan inventaris.",
          "Status pembelian dan hak melalui RevenueCat dan penyedia toko aplikasi.",
          "Metadata kerusakan dan diagnostik saat alat analitik/kerusakan diaktifkan.",
          "Persetujuan iklan dan metadata pengiriman iklan untuk pengguna non-Pro."
        ]
      },
      {
        "heading": "Pembelian",
        "body": [
          "Pembelian dalam aplikasi diproses melalui penagihan Apple App Store dan RevenueCat. Kami tidak menerima detail kartu pembayaran lengkap Anda. Status pembelian digunakan untuk membuka hak seperti Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Iklan dan Persetujuan",
        "body": [
          "Pengguna non-Pro mungkin melihat iklan interstisial. Kami menggunakan permintaan persetujuan jika diwajibkan oleh hukum. Anda dapat menghapus iklan paksa dengan membeli Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Penyimpanan dan Retensi",
        "body": [
          "Status permainan terutama disimpan secara lokal di perangkat atau browser Anda. Jika Anda menghapus aplikasi atau menghapus penyimpanan browser, kemajuan lokal dapat hilang kecuali sistem cadangan eksternal ditambahkan nanti."
        ]
      },
      {
        "heading": "Hak Anda",
        "body": [
          "Tergantung pada lokasi Anda, Anda mungkin memiliki hak untuk meminta akses, koreksi, penghapusan, atau pembatasan pemrosesan data pribadi."
        ]
      },
      {
        "heading": "Kontak",
        "body": [
          "Untuk permintaan privasi, hubungi: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "fr": {
    "title": "Politique de confidentialité",
    "lastUpdatedLabel": "Dernière mise à jour",
    "sections": [
      {
        "heading": "Aperçu",
        "body": [
          "Atomic Fusion Rush est un jeu de puzzle publié par EA Consulting. Cette politique explique quelles données sont traitées lorsque vous utilisez le jeu sur les versions web et mobiles natives."
        ]
      },
      {
        "heading": "Données que nous traitons",
        "body": [
          "Selon la plateforme et les fonctionnalités activées, nous pouvons traiter :"
        ],
        "list": [
          "Progression du jeu, tels que les niveaux, le score, les éléments découverts et l'inventaire.",
          "État d'achat et droits via RevenueCat et le fournisseur de l'App Store.",
          "Métadonnées de crash et de diagnostic lorsque les outils d'analyse/crash sont activés.",
          "Consentement publicitaire et métadonnées de diffusion d'annonces pour les utilisateurs non-Pro."
        ]
      },
      {
        "heading": "Achats",
        "body": [
          "Les achats intégrés sont traités via la facturation de l'Apple App Store et RevenueCat. Nous ne recevons pas les détails complets de votre carte de paiement. Le statut d'achat est utilisé pour débloquer des droits tels que Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Publicités et consentement",
        "body": [
          "Les utilisateurs non-Pro peuvent voir des publicités interstitielles. Nous utilisons des invites de consentement lorsque la loi l'exige. Vous pouvez supprimer les publicités forcées en achetant Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Stockage et conservation",
        "body": [
          "L'état du jeu est principalement stocké localement sur votre appareil ou votre navigateur. Si vous supprimez l'application ou effacez le stockage du navigateur, la progression locale peut être perdue à moins que des systèmes de sauvegarde externes ne soient ajoutés ultérieurement."
        ]
      },
      {
        "heading": "Vos droits",
        "body": [
          "Selon votre emplacement, vous pouvez avoir le droit de demander l'accès, la correction, la suppression ou la limitation du traitement des données personnelles."
        ]
      },
      {
        "heading": "Contact",
        "body": [
          "Pour les demandes de confidentialité, contactez : eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ko": {
    "title": "개인정보처리방침",
    "lastUpdatedLabel": "최종 업데이트",
    "sections": [
      {
        "heading": "개요",
        "body": [
          "Atomic Fusion Rush는 EA Consulting에서 배포하는 퍼즐 게임입니다. 본 정책은 웹 및 네이티브 모바일 빌드에서 게임을 사용할 때 처리되는 데이터를 설명합니다."
        ]
      },
      {
        "heading": "처리하는 데이터",
        "body": [
          "플랫폼 및 활성화된 기능에 따라 다음을 처리할 수 있습니다."
        ],
        "list": [
          "레벨, 점수, 발견된 요소 및 인벤토리와 같은 게임 플레이 진행 상황.",
          "RevenueCat 및 앱 스토어 제공업체를 통한 구매 상태 및 권한.",
          "분석/충돌 도구가 활성화된 경우 충돌 및 진단 메타데이터.",
          "Pro 사용자가 아닌 경우 광고 동의 및 광고 전달 메타데이터."
        ]
      },
      {
        "heading": "구매",
        "body": [
          "인앱 구매는 Apple App Store 청구 및 RevenueCat을 통해 처리됩니다. 당사는 귀하의 전체 결제 카드 정보를 받지 않습니다. 구매 상태는 Atomic Fusion Lifetime과 같은 권한을 잠금 해제하는 데 사용됩니다."
        ]
      },
      {
        "heading": "광고 및 동의",
        "body": [
          "Pro 사용자가 아닌 경우 전면 광고를 볼 수 있습니다. 당사는 법률에서 요구하는 경우 동의 프롬프트를 사용합니다. Atomic Fusion Lifetime을 구매하여 강제 광고를 제거할 수 있습니다."
        ]
      },
      {
        "heading": "저장 및 보존",
        "body": [
          "게임 플레이 상태는 주로 귀하의 장치 또는 브라우저에 로컬로 저장됩니다. 앱을 삭제하거나 브라우저 저장 공간을 지우면 외부 백업 시스템이 나중에 추가되지 않는 한 로컬 진행 상황이 손실될 수 있습니다."
        ]
      },
      {
        "heading": "귀하의 권리",
        "body": [
          "귀하의 위치에 따라 귀하는 개인 데이터에 대한 액세스, 수정, 삭제 또는 처리 제한을 요청할 권리가 있을 수 있습니다."
        ]
      },
      {
        "heading": "연락처",
        "body": [
          "개인 정보 보호 요청은 다음으로 문의하십시오: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "es": {
    "title": "Política de privacidad",
    "lastUpdatedLabel": "Última actualización",
    "sections": [
      {
        "heading": "Descripción general",
        "body": [
          "Atomic Fusion Rush es un juego de rompecabezas publicado por EA Consulting. Esta política explica qué datos se procesan cuando utilizas el juego en versiones web y móviles nativas."
        ]
      },
      {
        "heading": "Datos que procesamos",
        "body": [
          "Dependiendo de la plataforma y las funciones habilitadas, podemos procesar:"
        ],
        "list": [
          "Progreso del juego, como niveles, puntuación, elementos descubiertos e inventario.",
          "Estado de compra y derechos a través de RevenueCat y el proveedor de la tienda de aplicaciones.",
          "Metadatos de fallos y diagnósticos cuando las herramientas de análisis/fallos están habilitadas.",
          "Consentimiento publicitario y metadatos de entrega de anuncios para usuarios no Pro."
        ]
      },
      {
        "heading": "Compras",
        "body": [
          "Las compras dentro de la aplicación se procesan a través de la facturación de Apple App Store y RevenueCat. No recibimos los detalles completos de tu tarjeta de pago. El estado de la compra se utiliza para desbloquear derechos como Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Anuncios y consentimiento",
        "body": [
          "Los usuarios que no son Pro pueden ver anuncios intersticiales. Utilizamos avisos de consentimiento cuando lo exige la ley. Puedes eliminar los anuncios forzados comprando Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Almacenamiento y retención",
        "body": [
          "El estado del juego se almacena principalmente localmente en tu dispositivo o navegador. Si eliminas la aplicación o borras el almacenamiento del navegador, el progreso local puede perderse a menos que se agreguen sistemas de copia de seguridad externos más adelante."
        ]
      },
      {
        "heading": "Tus derechos",
        "body": [
          "Dependiendo de tu ubicación, puedes tener derecho a solicitar acceso, corrección, eliminación o limitación del procesamiento de datos personales."
        ]
      },
      {
        "heading": "Contacto",
        "body": [
          "Para solicitudes de privacidad, contacta a: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "vi": {
    "title": "Chính sách bảo mật",
    "lastUpdatedLabel": "Cập nhật lần cuối",
    "sections": [
      {
        "heading": "Tổng quan",
        "body": [
          "Atomic Fusion Rush là một trò chơi giải đố được xuất bản bởi EA Consulting. Chính sách này giải thích dữ liệu nào được xử lý khi bạn sử dụng trò chơi trên web và các bản dựng di động gốc."
        ]
      },
      {
        "heading": "Dữ liệu chúng tôi xử lý",
        "body": [
          "Tùy thuộc vào nền tảng và các tính năng được bật, chúng tôi có thể xử lý:"
        ],
        "list": [
          "Tiến độ chơi trò chơi như cấp độ, điểm số, các yếu tố được khám phá và kho đồ.",
          "Trạng thái mua hàng và quyền lợi thông qua RevenueCat và nhà cung cấp cửa hàng ứng dụng.",
          "Dữ liệu siêu dữ liệu sự cố và chẩn đoán khi các công cụ phân tích/sự cố được bật.",
          "Sự đồng ý quảng cáo và siêu dữ liệu phân phối quảng cáo cho người dùng không phải Pro."
        ]
      },
      {
        "heading": "Mua hàng",
        "body": [
          "Mua hàng trong ứng dụng được xử lý thông qua thanh toán của Apple App Store và RevenueCat. Chúng tôi không nhận được đầy đủ chi tiết thẻ thanh toán của bạn. Trạng thái mua hàng được sử dụng để mở khóa các quyền lợi như Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Quảng cáo và sự đồng ý",
        "body": [
          "Người dùng không phải Pro có thể thấy quảng cáo xen kẽ. Chúng tôi sử dụng lời nhắc đồng ý khi luật pháp yêu cầu. Bạn có thể xóa quảng cáo bắt buộc bằng cách mua Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Lưu trữ và giữ lại",
        "body": [
          "Trạng thái chơi trò chơi chủ yếu được lưu trữ cục bộ trên thiết bị hoặc trình duyệt của bạn. Nếu bạn xóa ứng dụng hoặc xóa bộ nhớ trình duyệt, tiến trình cục bộ có thể bị mất trừ khi các hệ thống sao lưu bên ngoài được thêm vào sau này."
        ]
      },
      {
        "heading": "Quyền của bạn",
        "body": [
          "Tùy thuộc vào vị trí của bạn, bạn có thể có quyền yêu cầu truy cập, chỉnh sửa, xóa hoặc hạn chế xử lý dữ liệu cá nhân."
        ]
      },
      {
        "heading": "Liên hệ",
        "body": [
          "Đối với các yêu cầu về quyền riêng tư, hãy liên hệ: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ru": {
    "title": "Политика конфиденциальности",
    "lastUpdatedLabel": "Последнее обновление",
    "sections": [
      {
        "heading": "Обзор",
        "body": [
          "Atomic Fusion Rush — это игра-головоломка, изданная EA Consulting. Эта политика объясняет, какие данные обрабатываются при использовании игры в веб-версии и нативных мобильных сборках."
        ]
      },
      {
        "heading": "Данные, которые мы обрабатываем",
        "body": [
          "В зависимости от платформы и включенных функций, мы можем обрабатывать:"
        ],
        "list": [
          "Прогресс игрового процесса, такой как уровни, очки, обнаруженные элементы и инвентарь.",
          "Состояние покупки и права через RevenueCat и поставщика магазина приложений.",
          "Метаданные сбоев и диагностики, когда включены инструменты аналитики/сбоев.",
          "Согласие на рекламу и метаданные доставки рекламы для пользователей, не являющихся Pro."
        ]
      },
      {
        "heading": "Покупки",
        "body": [
          "Покупки в приложении обрабатываются через биллинг Apple App Store и RevenueCat. Мы не получаем полные данные вашей платежной карты. Статус покупки используется для разблокировки прав, таких как Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Реклама и согласие",
        "body": [
          "Пользователи, не являющиеся Pro, могут видеть межстраничную рекламу. Мы используем запросы согласия там, где это требуется по закону. Вы можете удалить принудительную рекламу, купив Atomic Fusion Lifetime."
        ]
      },
      {
        "heading": "Хранение и сохранение",
        "body": [
          "Состояние игрового процесса в основном хранится локально на вашем устройстве или в браузере. Если вы удалите приложение или очистите хранилище браузера, локальный прогресс может быть потерян, если позже не будут добавлены внешние системы резервного копирования."
        ]
      },
      {
        "heading": "Ваши права",
        "body": [
          "В зависимости от вашего местоположения, вы можете иметь право запрашивать доступ, исправление, удаление или ограничение обработки персональных данных."
        ]
      },
      {
        "heading": "Контакты",
        "body": [
          "По вопросам конфиденциальности обращайтесь по адресу: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "zh-Hans": {
    "title": "隐私政策",
    "lastUpdatedLabel": "最后更新",
    "sections": [
      {
        "heading": "概述",
        "body": [
          "Atomic Fusion Rush是由EA Consulting发布的一款益智游戏。本政策解释了当您在网页和原生移动版本上使用游戏时，会处理哪些数据。"
        ]
      },
      {
        "heading": "我们处理的数据",
        "body": [
          "根据平台和启用的功能，我们可能会处理："
        ],
        "list": [
          "游戏进度，例如关卡、分数、发现的元素和库存。",
          "通过RevenueCat和应用商店提供商进行的购买状态和权益。",
          "当启用分析/崩溃工具时，崩溃和诊断元数据。",
          "非Pro用户的广告同意和广告投放元数据。"
        ]
      },
      {
        "heading": "购买",
        "body": [
          "应用内购买通过Apple App Store账单和RevenueCat处理。我们不会收到您的完整支付卡详细信息。购买状态用于解锁Atomic Fusion Lifetime等权益。"
        ]
      },
      {
        "heading": "广告和同意",
        "body": [
          "非Pro用户可能会看到插页式广告。在法律要求的情况下，我们使用同意提示。您可以通过购买Atomic Fusion Lifetime来移除强制广告。"
        ]
      },
      {
        "heading": "存储和保留",
        "body": [
          "游戏状态主要存储在您的设备或浏览器本地。如果您删除应用程序或清除浏览器存储，除非以后添加外部备份系统，否则本地进度可能会丢失。"
        ]
      },
      {
        "heading": "您的权利",
        "body": [
          "根据您所在的位置，您可能拥有请求访问、更正、删除或限制处理个人数据的权利。"
        ]
      },
      {
        "heading": "联系方式",
        "body": [
          "如需隐私请求，请联系：eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "hi": {
    "title": "गोपनीयता नीति",
    "lastUpdatedLabel": "अंतिम बार अपडेट किया गया",
    "sections": [
      {
        "heading": "अवलोकन",
        "body": [
          "एटॉमिक फ्यूजन रश ईए कंसल्टिंग द्वारा प्रकाशित एक पहेली गेम है। यह नीति बताती है कि जब आप वेब और नेटिव मोबाइल बिल्ड पर गेम का उपयोग करते हैं तो कौन सा डेटा संसाधित किया जाता है।"
        ]
      },
      {
        "heading": "हम जो डेटा संसाधित करते हैं",
        "body": [
          "प्लेटफ़ॉर्म और सक्षम सुविधाओं के आधार पर, हम संसाधित कर सकते हैं:"
        ],
        "list": [
          "गेमप्ले प्रगति जैसे स्तर, स्कोर, खोजे गए तत्व और इन्वेंट्री।",
          "रेवेन्यूकैट और ऐप स्टोर प्रदाता के माध्यम से खरीद की स्थिति और अधिकार।",
          "जब एनालिटिक्स/क्रैश टूल सक्षम होते हैं तो क्रैश और डायग्नोस्टिक मेटाडेटा।",
          "गैर-प्रो उपयोगकर्ताओं के लिए विज्ञापन सहमति और विज्ञापन-वितरण मेटाडेटा।"
        ]
      },
      {
        "heading": "खरीदें",
        "body": [
          "इन-ऐप खरीदारी ऐप्पल ऐप स्टोर बिलिंग और रेवेन्यूकैट के माध्यम से संसाधित की जाती है। हमें आपके पूर्ण भुगतान कार्ड विवरण प्राप्त नहीं होते हैं। खरीद की स्थिति का उपयोग एटॉमिक फ्यूजन लाइफटाइम जैसे अधिकारों को अनलॉक करने के लिए किया जाता है।"
        ]
      },
      {
        "heading": "विज्ञापन और सहमति",
        "body": [
          "गैर-प्रो उपयोगकर्ता अंतरालीय विज्ञापन देख सकते हैं। हम कानून द्वारा आवश्यक होने पर सहमति संकेतों का उपयोग करते हैं। आप एटॉमिक फ्यूजन लाइफटाइम खरीदकर जबरन विज्ञापनों को हटा सकते हैं।"
        ]
      },
      {
        "heading": "भंडारण और प्रतिधारण",
        "body": [
          "गेमप्ले स्थिति मुख्य रूप से आपके डिवाइस या ब्राउज़र पर स्थानीय रूप से संग्रहीत होती है। यदि आप ऐप को हटाते हैं या ब्राउज़र स्टोरेज साफ़ करते हैं, तो स्थानीय प्रगति खो सकती है जब तक कि बाद में बाहरी बैकअप सिस्टम नहीं जोड़े जाते।"
        ]
      },
      {
        "heading": "आपके अधिकार",
        "body": [
          "आपके स्थान के आधार पर, आपके पास व्यक्तिगत डेटा के लिए पहुंच, सुधार, विलोपन या प्रसंस्करण की सीमा का अनुरोध करने का अधिकार हो सकता है।"
        ]
      },
      {
        "heading": "संपर्क करें",
        "body": [
          "गोपनीयता अनुरोधों के लिए, संपर्क करें: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "de": {
    "title": "Datenschutzrichtlinie",
    "lastUpdatedLabel": "Zuletzt aktualisiert",
    "sections": [
      {
        "heading": "Übersicht",
        "body": [
          "Atomic Fusion Rush ist ein Puzzlespiel, das von EA Consulting veröffentlicht wird. Diese Richtlinie erklärt, welche Daten verarbeitet werden, wenn Sie das Spiel im Web und in nativen mobilen Builds nutzen."
        ]
      },
      {
        "heading": "Von uns verarbeitete Daten",
        "body": [
          "Je nach Plattform und aktivierten Funktionen können wir Folgendes verarbeiten:"
        ],
        "list": [
          "Spielfortschritt wie Level, Punktzahl, entdeckte Elemente und Inventar.",
          "Kaufstatus und Berechtigungen über RevenueCat und den App-Store-Anbieter.",
          "Absturz- und Diagnosemetadaten, wenn Analyse-/Absturz-Tools aktiviert sind.",
          "Werbeeinwilligung und Metadaten zur Anzeigenbereitstellung für Nicht-Pro-Benutzer."
        ]
      },
      {
        "heading": "Käufe",
        "body": [
          "In-App-Käufe werden über die Abrechnung des Apple App Store und RevenueCat abgewickelt. Wir erhalten nicht Ihre vollständigen Zahlungskartendaten. Der Kaufstatus wird verwendet, um Berechtigungen wie Atomic Fusion Lifetime freizuschalten."
        ]
      },
      {
        "heading": "Anzeigen und Zustimmung",
        "body": [
          "Nicht-Pro-Benutzer können Interstitial-Anzeigen sehen. Wir verwenden Zustimmungsaufforderungen, wo dies gesetzlich vorgeschrieben ist. Sie können erzwungene Anzeigen entfernen, indem Sie Atomic Fusion Lifetime kaufen."
        ]
      },
      {
        "heading": "Speicherung und Aufbewahrung",
        "body": [
          "Der Spielzustand wird hauptsächlich lokal auf Ihrem Gerät oder Browser gespeichert. Wenn Sie die App löschen oder den Browser-Speicher leeren, kann der lokale Fortschritt verloren gehen, es sei denn, es werden später externe Backup-Systeme hinzugefügt."
        ]
      },
      {
        "heading": "Ihre Rechte",
        "body": [
          "Je nach Ihrem Standort haben Sie möglicherweise das Recht, Zugang, Berichtigung, Löschung oder Einschränkung der Verarbeitung personenbezogener Daten zu beantragen."
        ]
      },
      {
        "heading": "Kontakt",
        "body": [
          "Für Datenschutzanfragen kontaktieren Sie: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  }
};

export const TERMS_CONTENT: Record<LegalLang, LegalDoc> = {
  "en": {
    "title": "Terms of Service",
    "lastUpdatedLabel": "Last updated",
    "sections": [
      {
        "heading": "Acceptance of Terms",
        "body": [
          "By using Atomic Fusion Rush, you agree to these Terms of Service and our Privacy Policy."
        ]
      },
      {
        "heading": "License to Use",
        "body": [
          "We grant you a limited, non-exclusive, non-transferable license to use the game for personal, non-commercial entertainment."
        ]
      },
      {
        "heading": "In-App Purchases",
        "body": [
          "Purchases are handled by the platform store and RevenueCat. All purchases are subject to the store's billing terms, refund policies, and regional rules."
        ]
      },
      {
        "heading": "Player Conduct",
        "body": [
          "You agree not to:"
        ],
        "list": [
          "Attempt to reverse engineer or tamper with purchase logic.",
          "Exploit bugs for unfair progression or unauthorized currency gain.",
          "Use automated scripts to abuse gameplay systems."
        ]
      },
      {
        "heading": "Availability and Changes",
        "body": [
          "We may update, change, or discontinue features at any time, including balancing, progression, and monetization systems."
        ]
      },
      {
        "heading": "Disclaimer and Liability",
        "body": [
          "The game is provided on an as-is basis, without warranties to the extent allowed by law. To the extent permitted by applicable law, we are not liable for indirect or consequential damages."
        ]
      },
      {
        "heading": "Contact",
        "body": [
          "Terms inquiries: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "it": {
    "title": "Termini di servizio",
    "lastUpdatedLabel": "Ultimo aggiornamento",
    "sections": [
      {
        "heading": "Accettazione dei Termini",
        "body": [
          "Utilizzando Atomic Fusion Rush, accetti i presenti Termini di servizio e la nostra Informativa sulla privacy."
        ]
      },
      {
        "heading": "Licenza d'uso",
        "body": [
          "Ti concediamo una licenza limitata, non esclusiva e non trasferibile per utilizzare il gioco per intrattenimento personale e non commerciale."
        ]
      },
      {
        "heading": "Acquisti in-app",
        "body": [
          "Gli acquisti sono gestiti dal negozio della piattaforma e da RevenueCat. Tutti gli acquisti sono soggetti ai termini di fatturazione, alle politiche di rimborso e alle regole regionali del negozio."
        ]
      },
      {
        "heading": "Condotta del giocatore",
        "body": [
          "Accetti di non:"
        ]
      },
      {
        "heading": "Disponibilità e modifiche",
        "body": [
          "Potremmo aggiornare, modificare o interrompere le funzionalità in qualsiasi momento, inclusi i sistemi di bilanciamento, progressione e monetizzazione."
        ]
      },
      {
        "heading": "Dichiarazione di non responsabilità e limitazione di responsabilità",
        "body": [
          "Il gioco è fornito così com'è, senza garanzie nella misura consentita dalla legge. Nella misura consentita dalla legge applicabile, non siamo responsabili per danni indiretti o consequenziali."
        ]
      },
      {
        "heading": "Contatti",
        "body": [
          "Richieste sui termini: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "pt-BR": {
    "title": "Termos de Serviço",
    "lastUpdatedLabel": "Última atualização",
    "sections": [
      {
        "heading": "Aceitação dos Termos",
        "body": [
          "Ao usar o Atomic Fusion Rush, você concorda com estes Termos de Serviço e nossa Política de Privacidade."
        ]
      },
      {
        "heading": "Licença de Uso",
        "body": [
          "Concedemos a você uma licença limitada, não exclusiva e intransferível para usar o jogo para entretenimento pessoal e não comercial."
        ]
      },
      {
        "heading": "Compras no Aplicativo",
        "body": [
          "As compras são gerenciadas pela loja da plataforma e pela RevenueCat. Todas as compras estão sujeitas aos termos de faturamento, políticas de reembolso e regras regionais da loja."
        ]
      },
      {
        "heading": "Conduta do Jogador",
        "body": [
          "Você concorda em não:"
        ]
      },
      {
        "list": [
          "Tentar fazer engenharia reversa ou adulterar a lógica de compra.",
          "Explorar bugs para progressão injusta ou ganho de moeda não autorizado.",
          "Usar scripts automatizados para abusar dos sistemas de jogo."
        ]
      },
      {
        "heading": "Disponibilidade e Alterações",
        "body": [
          "Podemos atualizar, alterar ou descontinuar recursos a qualquer momento, incluindo sistemas de balanceamento, progressão e monetização."
        ]
      },
      {
        "heading": "Isenção de Responsabilidade e Limitação de Responsabilidade",
        "body": [
          "O jogo é fornecido no estado em que se encontra, sem garantias, na extensão permitida por lei. Na extensão permitida pela lei aplicável, não somos responsáveis por danos indiretos ou consequenciais."
        ]
      },
      {
        "heading": "Contato",
        "body": [
          "Dúvidas sobre os termos: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "tr": {
    "title": "Hizmet Şartları",
    "lastUpdatedLabel": "Son güncelleme",
    "sections": [
      {
        "heading": "Şartların Kabulü",
        "body": [
          "Atomic Fusion Rush'ı kullanarak, bu Hizmet Şartlarını ve Gizlilik Politikamızı kabul etmiş olursunuz."
        ]
      },
      {
        "heading": "Kullanım Lisansı",
        "body": [
          "Size oyunu kişisel, ticari olmayan eğlence amaçlı kullanmanız için sınırlı, münhasır olmayan, devredilemez bir lisans veriyoruz."
        ]
      },
      {
        "heading": "Uygulama İçi Satın Almalar",
        "body": [
          "Satın almalar platform mağazası ve RevenueCat tarafından yürütülür. Tüm satın almalar mağazanın faturalandırma şartlarına, iade politikalarına ve bölgesel kurallarına tabidir."
        ]
      },
      {
        "heading": "Oyuncu Davranışı",
        "body": [
          "Şunları yapmamayı kabul edersiniz:"
        ],
        "list": [
          "Satın alma mantığını tersine mühendislikle çözmeye veya kurcalamaya çalışmak.",
          "Haksız ilerleme veya yetkisiz para kazanımı için hataları istismar etmek.",
          "Oyun sistemlerini kötüye kullanmak için otomatik komut dosyaları kullanmak."
        ]
      },
      {
        "heading": "Kullanılabilirlik ve Değişiklikler",
        "body": [
          "Dengeleme, ilerleme ve para kazanma sistemleri dahil olmak üzere özellikleri istediğimiz zaman güncelleyebilir, değiştirebilir veya durdurabiliriz."
        ]
      },
      {
        "heading": "Feragatname ve Sorumluluk",
        "body": [
          "Oyun, yasaların izin verdiği ölçüde garantisiz olarak 'olduğu gibi' sağlanır. Yürürlükteki yasaların izin verdiği ölçüde, dolaylı veya sonuç olarak ortaya çıkan zararlardan sorumlu değiliz."
        ]
      },
      {
        "heading": "İletişim",
        "body": [
          "Şartlar ile ilgili sorular: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ar": {
    "title": "شروط الخدمة",
    "lastUpdatedLabel": "آخر تحديث",
    "sections": [
      {
        "heading": "قبول الشروط",
        "body": [
          "باستخدامك Atomic Fusion Rush، فإنك توافق على شروط الخدمة هذه وسياسة الخصوصية الخاصة بنا."
        ]
      },
      {
        "heading": "ترخيص الاستخدام",
        "body": [
          "نمنحك ترخيصًا محدودًا وغير حصري وغير قابل للتحويل لاستخدام اللعبة للترفيه الشخصي غير التجاري."
        ]
      },
      {
        "heading": "المشتريات داخل التطبيق",
        "body": [
          "تتم معالجة المشتريات بواسطة متجر المنصة وRevenueCat. تخضع جميع المشتريات لشروط الفوترة الخاصة بالمتجر وسياسات استرداد الأموال والقواعد الإقليمية."
        ]
      },
      {
        "heading": "سلوك اللاعب",
        "body": [
          "أنت توافق على عدم:"
        ]
      },
      {
        "list": [
          "محاولة الهندسة العكسية أو التلاعب بمنطق الشراء.",
          "استغلال الأخطاء لتحقيق تقدم غير عادل أو الحصول على عملة غير مصرح بها.",
          "استخدام البرامج النصية الآلية لإساءة استخدام أنظمة اللعب."
        ]
      },
      {
        "heading": "التوفر والتغييرات",
        "body": [
          "قد نقوم بتحديث أو تغيير أو إيقاف الميزات في أي وقت، بما في ذلك أنظمة الموازنة والتقدم وتحقيق الدخل."
        ]
      },
      {
        "heading": "إخلاء المسؤولية والمسؤولية",
        "body": [
          "يتم توفير اللعبة على أساس \"كما هي\"، دون ضمانات بالقدر الذي يسمح به القانون. إلى الحد الذي يسمح به القانون المعمول به، نحن لسنا مسؤولين عن الأضرار غير المباشرة أو التبعية."
        ]
      },
      {
        "heading": "اتصل بنا",
        "body": [
          "استفسارات الشروط: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ja": {
    "title": "利用規約",
    "lastUpdatedLabel": "最終更新日",
    "sections": [
      {
        "heading": "規約への同意",
        "body": [
          "Atomic Fusion Rushをご利用になることにより、お客様は本利用規約および当社のプライバシーポリシーに同意するものとします。"
        ]
      },
      {
        "heading": "利用許諾",
        "body": [
          "当社は、お客様に個人的、非商業的な娯楽目的でゲームを使用するための、限定的、非独占的、譲渡不可能なライセンスを付与します。"
        ]
      },
      {
        "heading": "アプリ内購入",
        "body": [
          "購入はプラットフォームストアおよびRevenueCatによって処理されます。すべての購入は、ストアの請求条件、返金ポリシー、および地域規則に従います。"
        ]
      },
      {
        "heading": "プレイヤーの行動",
        "body": [
          "お客様は以下の行為を行わないことに同意するものとします。"
        ]
      },
      {
        "heading": "利用可能性と変更",
        "body": [
          "当社は、バランス調整、進行、収益化システムを含め、いつでも機能を更新、変更、または中止することができます。"
        ]
      },
      {
        "heading": "免責事項と責任",
        "body": [
          "本ゲームは、法律で許容される範囲において、いかなる保証もなく「現状有姿」で提供されます。適用される法律で許可される範囲において、当社は間接的または結果的な損害に対して責任を負いません。"
        ]
      },
      {
        "heading": "連絡先",
        "body": [
          "利用規約に関するお問い合わせ：eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "id": {
    "title": "Ketentuan Layanan",
    "lastUpdatedLabel": "Terakhir diperbarui",
    "sections": [
      {
        "heading": "Penerimaan Ketentuan",
        "body": [
          "Dengan menggunakan Atomic Fusion Rush, Anda menyetujui Ketentuan Layanan dan Kebijakan Privasi kami."
        ]
      },
      {
        "heading": "Lisensi Penggunaan",
        "body": [
          "Kami memberi Anda lisensi terbatas, non-eksklusif, tidak dapat dialihkan untuk menggunakan game ini untuk hiburan pribadi, non-komersial."
        ]
      },
      {
        "heading": "Pembelian Dalam Aplikasi",
        "body": [
          "Pembelian ditangani oleh toko platform dan RevenueCat. Semua pembelian tunduk pada ketentuan penagihan toko, kebijakan pengembalian dana, dan aturan regional."
        ]
      },
      {
        "heading": "Perilaku Pemain",
        "body": [
          "Anda setuju untuk tidak:"
        ],
        "list": [
          "Mencoba merekayasa balik atau merusak logika pembelian.",
          "Mengeksploitasi bug untuk kemajuan yang tidak adil atau perolehan mata uang yang tidak sah.",
          "Menggunakan skrip otomatis untuk menyalahgunakan sistem gameplay."
        ]
      },
      {
        "heading": "Ketersediaan dan Perubahan",
        "body": [
          "Kami dapat memperbarui, mengubah, atau menghentikan fitur kapan saja, termasuk sistem penyeimbangan, kemajuan, dan monetisasi."
        ]
      },
      {
        "heading": "Penafian dan Kewajiban",
        "body": [
          "Game ini disediakan apa adanya, tanpa jaminan sejauh diizinkan oleh hukum. Sejauh diizinkan oleh hukum yang berlaku, kami tidak bertanggung jawab atas kerusakan tidak langsung atau konsekuensial."
        ]
      },
      {
        "heading": "Kontak",
        "body": [
          "Pertanyaan ketentuan: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "fr": {
    "title": "Conditions d'utilisation",
    "lastUpdatedLabel": "Dernière mise à jour",
    "sections": [
      {
        "heading": "Acceptation des conditions",
        "body": [
          "En utilisant Atomic Fusion Rush, vous acceptez les présentes conditions d'utilisation et notre politique de confidentialité."
        ]
      },
      {
        "heading": "Licence d'utilisation",
        "body": [
          "Nous vous accordons une licence limitée, non exclusive et non transférable pour utiliser le jeu à des fins de divertissement personnel et non commercial."
        ]
      },
      {
        "heading": "Achats intégrés",
        "body": [
          "Les achats sont gérés par la boutique de la plateforme et RevenueCat. Tous les achats sont soumis aux conditions de facturation, aux politiques de remboursement et aux règles régionales de la boutique."
        ]
      },
      {
        "heading": "Conduite du joueur",
        "body": [
          "Vous vous engagez à ne pas :"
        ]
      },
      {
        "list": [
          "Tenter de désosser ou de manipuler la logique d'achat.",
          "Exploiter des bugs pour une progression injuste ou un gain de devise non autorisé.",
          "Utiliser des scripts automatisés pour abuser des systèmes de jeu."
        ]
      },
      {
        "heading": "Disponibilité et modifications",
        "body": [
          "Nous pouvons mettre à jour, modifier ou interrompre des fonctionnalités à tout moment, y compris les systèmes d'équilibrage, de progression et de monétisation."
        ]
      },
      {
        "heading": "Exclusion de garantie et limitation de responsabilité",
        "body": [
          "Le jeu est fourni tel quel, sans garanties dans la mesure permise par la loi. Dans la mesure permise par la loi applicable, nous ne sommes pas responsables des dommages indirects ou consécutifs."
        ]
      },
      {
        "heading": "Contact",
        "body": [
          "Demandes concernant les conditions : eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ko": {
    "title": "서비스 약관",
    "lastUpdatedLabel": "최종 업데이트",
    "sections": [
      {
        "heading": "약관 동의",
        "body": [
          "Atomic Fusion Rush를 사용함으로써 귀하는 본 서비스 약관 및 당사의 개인정보처리방침에 동의합니다."
        ]
      },
      {
        "heading": "사용 라이선스",
        "body": [
          "당사는 귀하에게 개인적, 비상업적 엔터테인먼트 목적으로 게임을 사용할 수 있는 제한적, 비독점적, 양도 불가능한 라이선스를 부여합니다."
        ]
      },
      {
        "heading": "인앱 구매",
        "body": [
          "구매는 플랫폼 스토어 및 RevenueCat에서 처리됩니다. 모든 구매는 스토어의 청구 약관, 환불 정책 및 지역 규칙에 따릅니다."
        ]
      },
      {
        "heading": "플레이어 행동",
        "body": [
          "귀하는 다음을 하지 않음에 동의합니다:"
        ],
        "list": [
          "구매 로직을 역설계하거나 조작하려는 시도.",
          "불공정한 진행 또는 무단 통화 획득을 위해 버그를 악용.",
          "게임 플레이 시스템을 남용하기 위해 자동화된 스크립트 사용."
        ]
      },
      {
        "heading": "가용성 및 변경",
        "body": [
          "당사는 균형, 진행 및 수익화 시스템을 포함하여 언제든지 기능을 업데이트, 변경 또는 중단할 수 있습니다."
        ]
      },
      {
        "heading": "면책 조항 및 책임",
        "body": [
          "게임은 법이 허용하는 범위 내에서 어떠한 보증도 없이 '있는 그대로' 제공됩니다. 관련 법률이 허용하는 범위 내에서 당사는 간접적 또는 결과적 손해에 대해 책임을 지지 않습니다."
        ]
      },
      {
        "heading": "연락처",
        "body": [
          "약관 문의: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "es": {
    "title": "Términos de servicio",
    "lastUpdatedLabel": "Última actualización",
    "sections": [
      {
        "heading": "Aceptación de los términos",
        "body": [
          "Al usar Atomic Fusion Rush, usted acepta estos Términos de servicio y nuestra Política de privacidad."
        ]
      },
      {
        "heading": "Licencia de uso",
        "body": [
          "Le otorgamos una licencia limitada, no exclusiva e intransferible para usar el juego con fines de entretenimiento personal y no comercial."
        ]
      },
      {
        "heading": "Compras dentro de la aplicación",
        "body": [
          "Las compras son gestionadas por la tienda de la plataforma y RevenueCat. Todas las compras están sujetas a los términos de facturación, políticas de reembolso y reglas regionales de la tienda."
        ]
      },
      {
        "heading": "Conducta del jugador",
        "body": [
          "Usted se compromete a no:"
        ]
      },
      {
        "heading": "Disponibilidad y cambios",
        "body": [
          "Podemos actualizar, cambiar o descontinuar funciones en cualquier momento, incluidos los sistemas de equilibrio, progresión y monetización."
        ]
      },
      {
        "heading": "Descargo de responsabilidad y responsabilidad",
        "body": [
          "El juego se proporciona tal cual, sin garantías en la medida permitida por la ley. En la medida permitida por la ley aplicable, no somos responsables de daños indirectos o consecuentes."
        ]
      },
      {
        "heading": "Contacto",
        "body": [
          "Consultas sobre los términos: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "vi": {
    "title": "Điều khoản dịch vụ",
    "lastUpdatedLabel": "Cập nhật lần cuối",
    "sections": [
      {
        "heading": "Chấp nhận Điều khoản",
        "body": [
          "Bằng cách sử dụng Atomic Fusion Rush, bạn đồng ý với các Điều khoản dịch vụ này và Chính sách quyền riêng tư của chúng tôi."
        ]
      },
      {
        "heading": "Giấy phép sử dụng",
        "body": [
          "Chúng tôi cấp cho bạn giấy phép có giới hạn, không độc quyền, không thể chuyển nhượng để sử dụng trò chơi cho mục đích giải trí cá nhân, phi thương mại."
        ]
      },
      {
        "heading": "Mua hàng trong ứng dụng",
        "body": [
          "Việc mua hàng được xử lý bởi cửa hàng nền tảng và RevenueCat. Tất cả các giao dịch mua đều tuân theo các điều khoản thanh toán, chính sách hoàn tiền và quy tắc khu vực của cửa hàng."
        ]
      },
      {
        "heading": "Hành vi của người chơi",
        "body": [
          "Bạn đồng ý không:"
        ]
      },
      {
        "list": [
          "Cố gắng đảo ngược kỹ thuật hoặc can thiệp vào logic mua hàng.",
          "Khai thác lỗi để tiến bộ không công bằng hoặc kiếm tiền trái phép.",
          "Sử dụng các tập lệnh tự động để lạm dụng hệ thống trò chơi."
        ]
      },
      {
        "heading": "Tính khả dụng và Thay đổi",
        "body": [
          "Chúng tôi có thể cập nhật, thay đổi hoặc ngừng cung cấp các tính năng bất cứ lúc nào, bao gồm các hệ thống cân bằng, tiến độ và kiếm tiền."
        ]
      },
      {
        "heading": "Tuyên bố từ chối trách nhiệm và Trách nhiệm pháp lý",
        "body": [
          "Trò chơi được cung cấp trên cơ sở nguyên trạng, không có bảo hành trong phạm vi pháp luật cho phép. Trong phạm vi pháp luật hiện hành cho phép, chúng tôi không chịu trách nhiệm về các thiệt hại gián tiếp hoặc do hậu quả."
        ]
      },
      {
        "heading": "Liên hệ",
        "body": [
          "Thắc mắc về điều khoản: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "ru": {
    "title": "Условия использования",
    "lastUpdatedLabel": "Последнее обновление",
    "sections": [
      {
        "heading": "Принятие условий",
        "body": [
          "Используя Atomic Fusion Rush, вы соглашаетесь с настоящими Условиями использования и нашей Политикой конфиденциальности."
        ]
      },
      {
        "heading": "Лицензия на использование",
        "body": [
          "Мы предоставляем вам ограниченную, неисключительную, непередаваемую лицензию на использование игры для личного, некоммерческого развлечения."
        ]
      },
      {
        "heading": "Покупки в приложении",
        "body": [
          "Покупки обрабатываются магазином платформы и RevenueCat. Все покупки регулируются условиями выставления счетов магазина, политикой возврата средств и региональными правилами."
        ]
      },
      {
        "heading": "Поведение игрока",
        "body": [
          "Вы соглашаетесь не:"
        ]
      },
      {
        "heading": "Доступность и изменения",
        "body": [
          "Мы можем обновлять, изменять или прекращать поддержку функций в любое время, включая системы балансировки, прогрессии и монетизации."
        ]
      },
      {
        "heading": "Отказ от ответственности и ограничение ответственности",
        "body": [
          "Игра предоставляется «как есть», без каких-либо гарантий в пределах, разрешенных законом. В пределах, разрешенных применимым законодательством, мы не несем ответственности за косвенные или последующие убытки."
        ]
      },
      {
        "heading": "Контакты",
        "body": [
          "Вопросы по условиям: eaconsulting.supp@gmail.com"
        ]
      }
    ],
    "list": [
      "Пытаться реконструировать или вмешиваться в логику покупки.",
      "Использовать ошибки для несправедливого прогресса или несанкционированного получения валюты.",
      "Использовать автоматизированные скрипты для злоупотребления игровыми системами."
    ]
  },
  "zh-Hans": {
    "title": "服务条款",
    "lastUpdatedLabel": "上次更新时间",
    "sections": [
      {
        "heading": "接受条款",
        "body": [
          "使用 Atomic Fusion Rush，即表示您同意本服务条款和我们的隐私政策。"
        ]
      },
      {
        "heading": "使用许可",
        "body": [
          "我们授予您有限的、非独占的、不可转让的许可，允许您将本游戏用于个人非商业娱乐。"
        ]
      },
      {
        "heading": "应用内购买",
        "body": [
          "购买由平台商店和 RevenueCat 处理。所有购买均受商店的计费条款、退款政策和地区规则的约束。"
        ]
      },
      {
        "heading": "玩家行为",
        "body": [
          "您同意不："
        ],
        "list": [
          "尝试逆向工程或篡改购买逻辑。",
          "利用漏洞获取不公平的进展或未经授权的货币。",
          "使用自动化脚本滥用游戏系统。"
        ]
      },
      {
        "heading": "可用性和变更",
        "body": [
          "我们可能随时更新、更改或停止功能，包括平衡、进展和货币化系统。"
        ]
      },
      {
        "heading": "免责声明和责任限制",
        "body": [
          "本游戏按“原样”提供，在法律允许的范围内不提供任何保证。在适用法律允许的范围内，我们不对间接或后果性损害承担责任。"
        ]
      },
      {
        "heading": "联系方式",
        "body": [
          "条款咨询：eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "hi": {
    "title": "सेवा की शर्तें",
    "lastUpdatedLabel": "अंतिम बार अपडेट किया गया",
    "sections": [
      {
        "heading": "शर्तों की स्वीकृति",
        "body": [
          "Atomic Fusion Rush का उपयोग करके, आप इन सेवा की शर्तों और हमारी गोपनीयता नीति से सहमत होते हैं।"
        ]
      },
      {
        "heading": "उपयोग करने का लाइसेंस",
        "body": [
          "हम आपको व्यक्तिगत, गैर-व्यावसायिक मनोरंजन के लिए गेम का उपयोग करने के लिए एक सीमित, गैर-अनन्य, गैर-हस्तांतरणीय लाइसेंस प्रदान करते हैं।"
        ]
      },
      {
        "heading": "इन-ऐप खरीदारी",
        "body": [
          "खरीदारी प्लेटफॉर्म स्टोर और RevenueCat द्वारा नियंत्रित की जाती है। सभी खरीदारी स्टोर के बिलिंग नियमों, वापसी नीतियों और क्षेत्रीय नियमों के अधीन हैं।"
        ]
      },
      {
        "heading": "खिलाड़ी आचरण",
        "body": [
          "आप सहमत हैं कि आप ऐसा नहीं करेंगे:"
        ]
      },
      {
        "list": [
          "खरीद तर्क को रिवर्स इंजीनियर करने या उसमें छेड़छाड़ करने का प्रयास करें।",
          "अनुचित प्रगति या अनधिकृत मुद्रा लाभ के लिए बग का फायदा उठाएं।",
          "गेमप्ले सिस्टम का दुरुपयोग करने के लिए स्वचालित स्क्रिप्ट का उपयोग करें।"
        ]
      },
      {
        "heading": "उपलब्धता और परिवर्तन",
        "body": [
          "हम किसी भी समय सुविधाओं को अपडेट, बदल या बंद कर सकते हैं, जिसमें संतुलन, प्रगति और मुद्रीकरण प्रणाली शामिल है।"
        ]
      },
      {
        "heading": "अस्वीकरण और देयता",
        "body": [
          "गेम यथा-स्थिति के आधार पर प्रदान किया जाता है, कानून द्वारा अनुमत सीमा तक वारंटी के बिना। लागू कानून द्वारा अनुमत सीमा तक, हम अप्रत्यक्ष या परिणामी नुकसान के लिए उत्तरदायी नहीं हैं।"
        ]
      },
      {
        "heading": "संपर्क करें",
        "body": [
          "शर्तों से संबंधित पूछताछ: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  },
  "de": {
    "title": "Nutzungsbedingungen",
    "lastUpdatedLabel": "Zuletzt aktualisiert",
    "sections": [
      {
        "heading": "Annahme der Bedingungen",
        "body": [
          "Durch die Nutzung von Atomic Fusion Rush stimmen Sie diesen Nutzungsbedingungen und unserer Datenschutzrichtlinie zu."
        ]
      },
      {
        "heading": "Nutzungslizenz",
        "body": [
          "Wir gewähren Ihnen eine beschränkte, nicht-exklusive, nicht übertragbare Lizenz zur Nutzung des Spiels für persönliche, nicht-kommerzielle Unterhaltungszwecke."
        ]
      },
      {
        "heading": "In-App-Käufe",
        "body": [
          "Käufe werden vom Plattform-Store und RevenueCat abgewickelt. Alle Käufe unterliegen den Abrechnungsbedingungen, Rückerstattungsrichtlinien und regionalen Regeln des Stores."
        ]
      },
      {
        "heading": "Spielerverhalten",
        "body": [
          "Sie stimmen zu, Folgendes zu unterlassen:"
        ]
      },
      {
        "list": [
          "Versuchen, die Kauflokik zu dekompilieren oder zu manipulieren.",
          "Fehler für unfaire Fortschritte oder unautorisierten Währungsgewinn auszunutzen.",
          "Automatisierte Skripte zu verwenden, um Spielsysteme zu missbrauchen."
        ]
      },
      {
        "heading": "Verfügbarkeit und Änderungen",
        "body": [
          "Wir können Funktionen jederzeit aktualisieren, ändern oder einstellen, einschließlich Balancing-, Fortschritts- und Monetarisierungssysteme."
        ]
      },
      {
        "heading": "Haftungsausschluss und Haftung",
        "body": [
          "Das Spiel wird im Ist-Zustand bereitgestellt, ohne Gewährleistungen, soweit gesetzlich zulässig. Soweit nach geltendem Recht zulässig, haften wir nicht für indirekte oder Folgeschäden."
        ]
      },
      {
        "heading": "Kontakt",
        "body": [
          "Anfragen zu den Bedingungen: eaconsulting.supp@gmail.com"
        ]
      }
    ]
  }
};
